#include<iostream>
#include<exception>

using namespace std;

class InvalidTemperatureException:public exception{};

template<typename T>
T convertToFahrenheit(T celsius){
    if(celsius<-273.15)throw InvalidTemperatureException();
    return(celsius*9/5)+32;
}

int main(){
    try{
        double c1=25;
        double f1=convertToFahrenheit(c1);
        cout<<c1<<" C = "<<f1<<" F"<<endl;

        double c2=-300;
        cout<<"Converting "<<c2<<" C to Fahrenheit"<<endl;
        double f2=convertToFahrenheit(c2);
        cout<<c2<<" C = "<<f2<<" F"<<endl;
    }catch(InvalidTemperatureException e){
        cout<<"Caught InvalidTemperatureException what(): "<<e.what()<<endl;
    }

    return 0;
}
